### ISSUE TITLE
regarding the task runner option

### ISSUE THREAD

**Issue by justefg** [AgentCosmic/xnotify#4]
i'm trying to copy a bunch of files from a folder to remote server whenever i modify them
`xnotify -i $SRC -e .git  -- ./copy.sh`
The problem I'm having is that I can't get modified paths. $1 and $2 seem not to work.
I'm running OSX 11.5

**Comment by AgentCosmic** [comment]
Program execution doesn't pass any arguments because you can do things like `xnotify -i . -- npm run log`.
If you need the arguments you can use a pipe instead.

**Comment by justefg** [comment]
Thanks for the reply and an amazing utility you've built @AgentCosmic.
Sorry, I didn't really get the part with `npm run log`.
The reason I wouldn't want to use a pipe is because the `--batch` option doesn't work with it.

**Comment by AgentCosmic** [comment]
Unfortunately that's the way it was designed. That's mainly because it needs to support commands which arguments as subcommands e.g. `git push`. And passing the file path as arguments would break it. But you have a good point. Getting the path info is quite useful. I'll have to make a breaking change. Let me think about it. Might do it over the weekend.

**Comment by justefg** [comment]
Would it possible to make `--batch` option work with a pipe?

**Comment by AgentCosmic** [comment]
I added the `--batch` option for piping. But I'm not sure how useful it would be. You can try the unrelease version first. https://we.tl/t-VuKkQFenk8

**Comment by AgentCosmic** [comment]
I added a batch terminator so it works with xargs https://we.tl/t-AUveFAwCIY
It defaults to null character so you can use the `--null` or `-0` argument on xargs to trigger by batches.

**Comment by justefg** [comment]
thanks a lot
